name: Github Personal Website
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git ls-remote --exit-code --heads origin gh-pages; then
            git push origin --delete gh-pages || true
          fi
          git checkout --orphan gh-pages
          npm run build
          rm -rf README.md index.html node_modules package-lock.json package.json public src tailwind.config.js vite.config.js
          mv -f dist/* .
          rm -rf dist
          ls -l